configuration:
  runtime: "concord-v2"
  arguments:
    myName: shubham
  debug: true

triggers:
  - github:
      version: 2
      entryPoint: default
      conditions:
        type: "push"
        
flows:
  default:
  - log: "Hello, Concord User"
  - log: "Say hello to ${myName}"